### ISSUE TITLE
New release is required to make this lib work with newest typescript.

### ISSUE THREAD

**Issue by pubkey** [thenativeweb/get-graphql-from-jsonschema#361]
Running this library with the newest typescript version does not work.
Most likely because of the outdated `defekt` library.
This was already fixed by the dependabot which increased the `defekt` version in the package.json.

Can you make a new release of this library so the fixes are pushed upstream?

@goloroden

**Comment by goloroden** [comment]
Happening in #362

**Comment by pubkey** [comment]
That was fast :)

**Comment by pubkey** [comment]
@goloroden 
I have exactly the same problem again :)
`defekt` is now on 9.2.0 which was updated in this repo by dependabot.
We need this to support typescript 4.7.4.
Can you make a new release?

**Comment by goloroden** [comment]
@pubkey Of course 😊

The new version has just been published as `8.0.18` 🎉

**Comment by pubkey** [comment]
Dankeschön!
